const bgStylePokemonType = {
    grass: "bg-gradient-to-b from-[#9bd3c6] to-[#c6df9f]",
    bug: "bg-gradient-to-b from-green-500 to-green-300",
    fire: "bg-gradient-to-b from-orange-500 to-orange-300",
    water: "bg-gradient-to-b from-blue-500 to-blue-300",
    normal: "bg-gradient-to-b from-[#79545c] to-pink-300",
    rock: "bg-gradient-to-b from-gray-600 to-gray-300",
    fighting: "bg-gradient-to-b from-[#a3452d] to-[#c55133]",
    poison: "bg-gradient-to-b from-[#6f3f9e] to-[#b073eb]",
    ground: "bg-gradient-to-b from-[#744b10] to-[#ad7728]",
    ghost: "bg-gradient-to-b from-[#373b7b] to-[#5c62bf]",
    steel: "bg-gradient-to-b from-[#667b74] to-[#8c9793]",
    electric: "bg-gradient-to-b from-[#181f98] to-[#4f55bb]",
    psychic: "bg-gradient-to-b from-[#a62551] to-[#c95e82]",
    ice: "bg-gradient-to-b from-[#6cc1e5] to-[#90dafa]",
    dragon: "bg-gradient-to-b from-[#4d949e] to-[#7fb2b9]",
    dark: "bg-gradient-to-b from-[#050908] to-[#303534]",
    fairy: "bg-gradient-to-b from-pink-950 to-pink-300",

  }

  const bgImageStylePokemonType = {
    grass: "bg-[url(/images/bg-grass.png)]",
    bug: "bg-[url(/images/bg-bug.png)]",
    fire: "bg-[url(/images/bg-fire.png)]",
    water: "bg-[url(/images/bg-water.png)]",
    normal: "bg-[url(/images/bg-normal.png)]",
    rock: "bg-[url(/images/bg-rock.png)]",
    fighting: "bg-[url(/images/bg-fighting.png)]",
    poison: "bg-[url(/images/bg-poison.png)]",
    ground: "bg-[url(/images/bg-ground.png)]",
    ghost: "bg-[url(/images/bg-ghost.png)]",
    steel: "bg-[url(/images/bg-steel.png)]",
    electric: "bg-[url(/images/bg-electric.png)]",
    psychic: "bg-[url(/images/bg-psychic.png)]",
    ice: "bg-[url(/images/bg-ice.png)]",
    dragon: "bg-[url(/images/bg-dragon.png)]",
    dark: "bg-[url(/images/bg-dark.png)]",
    fairy: "bg-[url(/images/bg-fairy.png)]",
  }
  /* ejemplo pero solo img */
  const ImageStylePokemonType = {
    grass: "/images/bg-grass.png",
    bug: "/images/bg-bug.png",
    fire: "/images/bg-fire.png",
    water: "/images/bg-water.png",
    normal: "/images/bg-normal.png",
    rock: "/images/bg-rock.png",
    fighting: "/images/bg-fighting.png",
    poison: "/images/bg-poison.png",
    ground: "/images/bg-ground.png",
    ghost: "/images/bg-ghost.png",
    steel: "/images/bg-steel.png",
    electric: "/images/bg-electric.png",
    psychic: "/images/bg-psychic.png",
    ice: "/images/bg-ice.png",
    dragon: "/images/bg-dragon.png",
    dark: "/images/bg-dark.png",
    fairy: "/images/bg-fairy.png",
  }
  /*aca termina mi img */

  const borderStylePokemonType = {
    grass: "border-[5px] border-green-800",
    bug: "border-[5px] border-green-500",
    fire: "border-[5px] border-orange-500",
    water: "border-[5px] border-blue-500",
    normal: "border-[5px] border-pink-950",
    rock: "border-[5px] border-gray-600",
    fighting: "border-[5px] border-[#a3452d]",
    poison: "border-[5px] border-[#6f3f9e]",
    ground: "border-[5px] border-[#744b10]",
    ghost: "border-[5px] border-[#373b7b]",
    steel: "border-[5px] border-[#667b74]",
    electric: "border-[5px] border-[#181f98]",
    psychic: "border-[5px] border-[#a62551]",
    ice: "border-[5px] border-[#6cc1e5]",
    dragon: "border-[5px] border-[#4d949e]",
    dark: "border-[5px] border-[#050908]",
    fairy: "border-[5px] border-pink-950",

  }

  const nameStylePokemon = {
    grass: "text-lime-600",
    fire: "text-red-500",
    water: "text-blue-500",
    bug: "text-green-500",
    normal: "text-pink-600",
    rock: "text-gray-600",
    fighting: "text-[#c55133]",
    poison: "text-[#b073eb]",
    ground: "text-[#ad7728]",
    ghost: "text-[#373b7b]",
    steel: "text-[#667b74]",
    electric: "text-[#181f98]",
    psychic: "text-[#a62551]",
    ice: "text-[#6cc1e5]",
    dragon: "text-[#4d949e]",
    dark: "text-[#050908]",
    fairy: "text-pink-950",
  }

  const numberStylePokemon = {
    grass: "text-lime-600",
    fire: "text-red-500",
    water: "text-blue-500",
    bug: "text-green-500",
    normal: "text-pink-600",
    fighting: "text-[#c55133]",
    poison: "text-[#b073eb]",
    ground: "text-[#ad7728]",
    ghost: "text-[#373b7b]",
    steel: "text-[#667b74]",
    electric: "text-[#181f98]",
    psychic: "text-[#a62551]",
    ice: "text-[#6cc1e5]",
    dragon: "text-[#4d949e]",
    dark: "text-[#050908]",
    fairy: "text-pink-950",
  }

  export{
    bgStylePokemonType,
    bgImageStylePokemonType,
    ImageStylePokemonType,
    borderStylePokemonType,
    nameStylePokemon,
    numberStylePokemon, 
  }